- name: Set timezone
  community.general.timezone:
    name: "{{ system_timezone }}"
  become: true

- name: Update and upgrade apt packages
  become: true
  ansible.builtin.package:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400

- name: Install essential admin packages
  ansible.builtin.package:
    name:
      - htop
      - curl
    state: present
  become: true
